### ISSUE TITLE
Add nameplate popup to top left action buttons

### ISSUE THREAD

**Issue by zeke2856** [KacperLa/KacperLa.github.io#1]
<img width="331" alt="Screenshot 2024-11-04 at 5 27 06 PM" src="https://github.com/user-attachments/assets/0c6b728a-b452-4145-a05d-504a54ee6b69">

**Comment by zeke2856** [comment]
It would be nice

**Comment by KacperLa** [comment]
Issue has been addressed here: 754ed90
Button now display text when a user hover over them.

**Comment by KacperLa** [comment]
Issue has been addressed here: https://github.com/KacperLa/SpudBuddy/commit/754ed909a3fea6cfeff1855f6c397e687263b344
Buttons now display text when a user hover over them.
